services:
  apigateway:
    build:
      context: ./APIGateway/APIGateway
    ports:
      - "7007:443"
    volumes:
      - ./https:/https:ro
    environment:
      ASPNETCORE_Kestrel__Endpoints__Https__Url: "https://+:443"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/aspnetapp.pfx"
      ASPNETCORE_Kestrel__Certificates__Default__Password: ${CERT_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ISSUER: ${JWT_ISSUER}
      JWT_AUDIENCE: ${JWT_AUDIENCE}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - userservice
      - orderservice
      - productservice
      - paymentservice
    networks:
      - app-network

  userservice:
    build:
      context: ./UserService
    environment:
      - ConnectionStrings__DefaultConnection=Server=userdb;Database=UsersDatabase;User=sa;Password=${SA_PASSWORD};Encrypt=True;TrustServerCertificate=True
      - JwtSettings__Secret=${JWT_SECRET}
      - JwtSettings__Issuer=${JWT_ISSUER}
      - JwtSettings__Audience=${JWT_AUDIENCE}
      - JwtSettings__ExpiryMinutes=60
    depends_on:
      - userdb
    networks:
      - app-network

  userdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - app-network

  orderservice:
    build:
      context: ./OrderService/OrderService
    environment:
      - ConnectionStrings__DefaultConnection=Server=orderdb;Database=OrdersDatabase;User=sa;Password=${SA_PASSWORD};Encrypt=True;TrustServerCertificate=True
    depends_on:
      - orderdb
      - rabbitmq
    networks:
      - app-network

  orderdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - "1434:1433"
    networks:
      - app-network

  productservice:
    build:
      context: ./ProductService/ProductService
    environment:
      - ConnectionStrings__DefaultConnection=Server=productdb;Database=ProductsDatabase;User=sa;Password=${SA_PASSWORD};Encrypt=True;TrustServerCertificate=True
      - JwtSettings__Secret=${JWT_SECRET}
      - JwtSettings__Issuer=${JWT_ISSUER}
      - JwtSettings__Audience=${JWT_AUDIENCE}
    depends_on:
      - productdb
      - rabbitmq
    volumes:
      - ./ProductService/wwwroot/images:/app/wwwroot/images
    networks:
      - app-network

  productdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - "1435:1433"
    networks:
      - app-network

  paymentservice:
    build:
      context: ./PaymentService
    environment:
      - ConnectionStrings__DefaultConnection=Server=paymentdb;Database=PaymentsDatabase;User=sa;Password=${SA_PASSWORD};Encrypt=True;TrustServerCertificate=True
      - Braintree__Environment=${BRAINTREE_ENVIRONMENT}
      - Braintree__MerchantId=${BRAINTREE_MERCHANT_ID}
      - Braintree__PublicKey=${BRAINTREE_PUBLIC_KEY}
      - Braintree__PrivateKey=${BRAINTREE_PRIVATE_KEY}
      - Redis__ConnectionString=redis:6379
    depends_on:
      - paymentdb
      - redis
      - rabbitmq
    networks:
      - app-network

  paymentdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - "1436:1433"
    networks:
      - app-network

  recommendationservice:
    build:
      context: ./RecommendationService
    environment:
      - ConnectionStrings__DefaultConnection=Server=recommendationdb;Database=RecommendationsDatabase;User=sa;Password=${SA_PASSWORD};Encrypt=True;TrustServerCertificate=True
    depends_on:
      - recommendationdb
      - rabbitmq
    networks:
      - app-network

  recommendationdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - "1437:1433"
    networks:
      - app-network

  redis:
    image: redis:alpine
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - app-network

networks:
  app-network:
