apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paymentdb-pvc
  namespace: retailro
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentdb
  namespace: retailro
  labels:
    app: paymentdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymentdb
  template:
    metadata:
      labels:
        app: paymentdb
    spec:
      containers:
        - name: mssql
          image: mcr.microsoft.com/mssql/server:2022-latest
          ports:
            - containerPort: 1433
          env:
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SA_PASSWORD
            - name: ACCEPT_EULA
              value: "Y"
          volumeMounts:
            - name: mssql-data
              mountPath: /var/opt/mssql
      volumes:
        - name: mssql-data
          persistentVolumeClaim:
            claimName: paymentdb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: paymentdb
  namespace: retailro
spec:
  selector:
    app: paymentdb
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: ClusterIP
